name: Deploy frontend to GCS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "development" branch
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node.js 18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: "18.12.1"

      - name: Build of frontend app
        env:
          PUBLIC_APP_NAME: ${{ vars.SHARE_APP_NAME }}
          PUBLIC_API_BASEURI: ${{ vars.SHARE_API_BASEURI }}
          PUBLIC_API_VERSION: ${{ vars.SHARE_API_VERSION }}
          PRIVATE_API_KEY: ${{ vars.SHARE_API_KEY }}
        run: |
          yarn
          yarn build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCS_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Sync static folder at GCS bucket
        run: gsutil rsync -d -r ./build gs://${{ vars.SHARE_DOMAIN }}
